### ISSUE TITLE
Is there a complete example workflow for running REFINED to generate images of tabular data?

### ISSUE THREAD

**Issue by zhuyitan** [omidbazgirTTU/REFINED#1]
Dear Omid Bazgir,

First, congratulations on publishing REFINED on Nature Communications. It's an outstanding work and I want to use it to generate images of some tabular data in my research. 

However, the workflow currently included in the repository seems incomplete. For example, the Synthetic_Data.py script needs to use REFINED_Im_Gen function in Toolbox to generate images using the REFINED algorithm. But the Toolbox.py script does not provide the REFINED_Im_Gen function.

I am wondering whether there is any runnable example workflow, which I can adapt to generate images for my own tabular data.

Thank you very much.

Yitan Zhu

**Comment by omidbazgirTTU** [comment]
Thanks for your interest in our paper, and sorry for the inconvenience. I have updated the Toolbox.py, and now it contains all the functions you need. Also, an example is added for running the hill-climbing code. Please let me know if anything else is needed.
